// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("CommandLineParser")]
[assembly: AssemblyDescriptionAttribute("The Command Line Parser Library offers to CLR applications a clean and concise API for manipulating command line arguments and related tasks.")]
[assembly: AssemblyProductAttribute("CommandLineParser")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2005 - 2013 Giacomo Stelluti Scala")]
[assembly: InternalsVisibleToAttribute("CommandLine.Tests, PublicKey=002400000480000094000000060200000024000052534131000400000100010015eb7571d696c075627830f9468969103bc35764467bdbccfc0850f2fbe6913ee233d5d7cf3bbcb870fd42e6a8cc846d706b5cef35389e5b90051991ee8b6ed73ee1e19f108e409be69af6219b2e31862405f4b8ba101662fbbb54ba92a35d97664fe65c90c2bebd07aef530b01b709be5ed01b7e4d67a6b01c8643e42a20fb4")]
[assembly: AssemblyVersionAttribute("1.10.0.1")]
[assembly: AssemblyFileVersionAttribute("1.10.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.10.0-unstable.1+1.Branch.develop.Sha.3313380570dbf146b52f072dcf215e2369ff4160")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.10.0.1";
    }
}
